language: node_js

dist: xenial

node_js:
    - "13"
    - "12"
    - "10"

cache: yarn

if: tag IS blank

script:
    - set -e
    - yarn run lerna bootstrap
    - yarn run lint
    - yarn run prettier:check
    - yarn run build
    - set +e

jobs:
    include:
        - stage: Publish docs
          if: type = push AND fork = false AND tag IS blank AND !(branch =~ /^dependabot\//) AND !(branch =~ /^all-contributors\//)
          script: lerna bootstrap && lerna run build && scripts/travis/publishDocs.sh
